<?php
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

class Users extends REST_Controller {

    public function __construct($config = 'rest') {
        parent::__construct($config);
        $this->methods['users_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['users_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['users_delete']['limit'] = 50; // 50 requests per hour per user/key
        $this->load->database();
    }

    public function index_get() 
    {
        $id_user = $this->get('id_user');
        if ($id_user == '') {
            $users = $this->db->get('users')->result();
        } else {
            $this->db->where('id_user', $id_user);
            $users = $this->db->get('users')->result();
        }
        $this->response($users, REST_Controller::HTTP_OK);
    }

    public function index_post()
    {
        $data = array(
            'id_user' => $this->post('id_user'), // Automatically generated by the model
            'username' => $this->post('username'),
            'password' => $this->post('password'),
            'namarental' => $this->post('namarental'),
            'email' => $this->post('email'),
            'logo' => $this->post('logo'),
            'nohp' => $this->post('nohp'),
            'bio' => $this->post('bio'),
            'level' => $this->post('level')
        );

        $insert = $this->db->insert('users', $data);
        if ($insert) {
            $this->response($data, REST_Controller::HTTP_CREATED);
        }
    }

    public function index_put()
    {
        $id_user = $this->put('id_user');
        $data = array(
                    'id_user' => $this->post('id_user'), // Automatically generated by the model
                    'username' => $this->post('username'),
                    'password' => $this->post('password'),
                    'namarental' => $this->post('namarental'),
                    'email' => $this->post('email'),
                    'logo' => $this->post('logo'),
                    'nohp' => $this->post('nohp'),
                    'bio' => $this->post('bio'),
                    'level' => $this->post('level')
                );
        $this->db->where('id_user', $id_user);
        $update = $this->db->update('users', $data);
        if ($update) {
            $this->response($data,  REST_Controller::HTTP_OK);
        } else {
            $this->response(array('status' => 'FALSE', REST_Controller::HTTP_NOT_FOUND));
        }
    }

    public function index_delete()
    {
        $id_user = $this->delete('id_user');
        $this->db->where('id_user', $id_user);
        $delete = $this->db->delete('users');
        if ($delete) {
            $this->response(array('status' => 'success'), REST_Controller::HTTP_OK);
        } else {
            $this->response(array('status' => 'FALSE', REST_Controller::HTTP_NOT_FOUND));
        }
    }
}
