<?php
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

class Vehicle extends REST_Controller {

    public function __construct($config = 'rest') {
        parent::__construct($config);
        $this->methods['users_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['users_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['users_delete']['limit'] = 50; // 50 requests per hour per user/key
        $this->load->database();
    }

    function index_get() 
    {
        $id_vehicle = $this->get('id_vehicle');
        if ($id_vehicle == '') {
            $users = $this->db->get('vehicle')->result();
        } else {
            $this->db->where('id_vehicle', $id_vehicle);
            $users = $this->db->get('vehicle')->result();
        }
        $this->response($users, REST_Controller::HTTP_OK);
    }

    public function index_post()
    {
        $data = array(
            'id_vehicle' => $this->post('id_vehicle'), // Automatically generated by the model
            'id_user' => $this->post('id_user'),
            'plat' => $this->post('plat'),
            'kategori' => $this->post('kategori'),
            'jenis' => $this->post('jenis'),
            'merk' => $this->post('merk'),
            'jmlseat' => $this->post('jmlseat'),
            'harga' => $this->post('harga'),
            'driver' => $this->post('driver'),
            'foto' => $this->post('foto')
        );

        $insert = $this->db->insert('vehicle', $data);
        if ($insert) {
            $this->response($data, REST_Controller::HTTP_CREATED);
        }
    }

    public function index_put()
    {
        $id_vehicle = $this->put('id_vehicle');
        $data = array(
                    'id_vehicle' => $this->post('id_vehicle'), // Automatically generated by the model
                    'id_user' => $this->post('id_user'),
                    'plat' => $this->post('plat'),
                    'kategori' => $this->post('kategori'),
                    'jenis' => $this->post('jenis'),
                    'merk' => $this->post('merk'),
                    'jmlseat' => $this->post('jmlseat'),
                    'harga' => $this->post('harga'),
                    'driver' => $this->post('driver'),
                    'foto' => $this->post('foto')
                );
        $this->db->where('id_vehicle', $id_vehicle);
        $update = $this->db->update('vehicle', $data);
        if ($update) {
            $this->response($data,  REST_Controller::HTTP_OK);
        } else {
            $this->response(array('status' => 'FALSE', REST_Controller::HTTP_NOT_FOUND));
        }
    }

    public function index_delete()
    {
        $id_vehicle = $this->delete('id_vehicle');
        $this->db->where('id_vehicle', $id_vehicle);
        $delete = $this->db->delete('vehicle');
        if ($delete) {
            $this->response(array('status' => 'success'), REST_Controller::HTTP_OK);
        } else {
            $this->response(array('status' => 'FALSE', REST_Controller::HTTP_NOT_FOUND));
        }
    }
}
